{
 "title": "New dashboard",
 "time": { "from": "2022-01-31T21:00:00.000Z", "to": "2022-02-27T21:00:00.000Z" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "select timestamp, prediction_drift from dummy_metrics;"
    }
   ]
  },
  {
   "title": "Share Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select timestamp, share_missing_values from dummy_metrics;"
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select timestamp, num_drifted_columns from dummy_metrics;"
    }
   ]
  }
 ]
}