{
 "title": "Homework Dashboard",
 "time": { "from": "2024-02-29T21:00:00.000Z", "to": "2024-03-31T20:59:59.000Z" },
 "panels": [
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT timestamp, prediction_drift FROM dummy_metrics;"
    }
   ]
  },
  {
   "title": "Current Data Quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "select timestamp, quantile from dummy_metrics"
    }
   ]
  },
  {
   "title": "Number of Drifted Columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "select timestamp, num_drifted_columns from dummy_metrics;"
    }
   ]
  },
  {
   "title": "Share Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "select timestamp, share_missing_values from dummy_metrics "
    }
   ]
  }
 ]
}